name = "OmronD6FPH"
uuid = "c57aa17a-835b-45aa-83d3-6d56014591bd"
authors = ["Markus Petters"]
version = "0.1.0"

[compat]
julia = "1.4.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
